### ISSUE TITLE
codecov  "Waiting for status to be reported" for no reasons

### ISSUE THREAD

**Issue by ssbarnea** [codecov/feedback#269] opened 2024-02-08 11:25 UTC
**Describe the bug**
I am seeing "Waiting for status to be reported" on a number of repositories which are identically configured as others and where I am sure that the upload happened.

Even on codecov.io website it is clearly visible that those PRs had the reports uploaded and should be passing, but the information never reaches github, and we are unable to merge the PRs because we marked "codecov/project" as a required check.

I am 100% sure that the affected repositories are active on [github app](https://github.com/apps/codecov/installations/398480)

I also carefully read the https://codecovpro.zendesk.com/hc/en-us/articles/15822217861531-Statuses-or-Checks-Not-Displaying-on-Pull-Request-Merge-Request document, but the document does not provide any usable workaround.

**Expected behavior**

Be able to force codecov to report the status.

**Screenshots**

![](https://sbarnea.com/ss/Screen-Shot-2024-02-08-11-13-39.31.png)
![](https://sbarnea.com/ss/Screen-Shot-2024-02-08-11-13-20.13.png)

**Additional context**

I mention that his problem is not unique to this project and I was able to produce it in 6-7 other repositories. Basically I think that it is happening in >50 of the projects where we are using codecov in this organization.

Clearly codecov.io database keeps a valid status regarding these pull requests.

As this CodeCov App reporting seems to be quite unreliable, I am wondering why codecov did not provide a reusable github action that can be used to check the status of a specific pull-request. 

That can easily be integrated in our github workflows and remove the need to rely on an external service that is like a black box. if it does reply or not is more like a roulette and when it fails we have no way of knowing why, something that would not happen with a reusable github action.

The status is freely open, and checking it should not more than a simple curl check.

**Comment by skateman** [comment] 2024-02-08 11:54
Experiencing the same problem [on our repo](https://github.com/RedHatInsights/compliance-backend)

**Comment by ssbarnea** [comment] 2024-02-08 12:19
I tried to use curl and codecov API to identify if a specific PR is considered to be passing codecov check but... bad luck, apparently even the v2 api seems to not provide information about increased or decreased coverage. Take a look:

```
+ curl --request GET --url https://api.codecov.io/api/v2/github/ansible/repos/molecule/pulls/4132/ --header 'accept: application/json'
{"pullid":4132,"title":"GHA maintenance","base_totals":{"files":55,"lines":2400,"hits":2193,"misses":207,"partials":0,"coverage":91.38,"branches":0,"methods":0,"sessions":4,"complexity":0.0,"complexity_total":0.0,"complexity_ratio":0,"diff":0},"head_totals":{"files":55,"lines":2400,"hits":2192,"misses":208,"partials":0,"coverage":91.33,"branches":0,"methods":0,"sessions":4,"complexity":0.0,"complexity_total":0.0,"complexity_ratio":0,"diff":0},"updatestamp":"2024-02-07T16:12:44.150918Z","state":"open","ci_passed":true,"author":{"service":"github","username":"ssbarnea","name":"Sorin Sbarnea"}}+ echo '---\n\n'

# ^ that PR is supposed to be a passing coverage one

+ curl --request GET --url https://api.codecov.io/api/v2/github/ansible/repos/ansible-creator/pulls/78/ --header 'accept: application/json'
{"pullid":78,"title":"Add a new `--templates-path` option","base_totals":{"files":12,"lines":457,"hits":371,"misses":86,"partials":0,"coverage":81.18,"branches":0,"methods":0,"sessions":10,"complexity":0.0,"complexity_total":0.0,"complexity_ratio":0,"diff":0},"head_totals":{"files":12,"lines":481,"hits":381,"misses":100,"partials":0,"coverage":79.21,"branches":0,"methods":0,"sessions":5,"complexity":0.0,"complexity_total":0.0,"complexity_ratio":0,"diff":0},"updatestamp":"2024-02-07T14:24:17.098644Z","state":"open","ci_passed":true,"author":{"service":"github","username":"pre-commit-ci[bot]","name":"pre-commit-ci[bot]"}}%

# ^ that PR is supposed to be one that lowered coverage, so it should trigger a failure
```

Sadly, I was not able to find the needed information returned by the API as only overall results were returned. Still from the practical point of view knowing the exact coverage is irrelevant, we only want to know if it did decrease or not, so we can decide the outcome of the job.

I guess that we could compute the diff in coverage by subtracting the value from inside `base_total` and the one from inside `head_totals`,  but that is missing another factor, the threshold and we would have to read the configuration to identify if a threshold was configured. I was hoping the the API would be able to provide a higher level access where we could just get a `coverage_passed: true` or `false`.

Maybe someone managed to write a script that can easily be used as a github action that does that?

**Comment by ssbarnea** [comment] 2024-02-09 14:44
With zero replies from support and lack of activity, I was forced to build an reusable action that can replace the app. See https://github.com/marketplace/actions/codecov-io-status and feel free to contribute to improve it.

At least if that one fails, you can see why, and even retry it.

**Comment by rohan-at-sentry** [comment] 2024-02-09 16:48
@ssbarnea - I'm a PM on the Codecov team. Apologies for the late response, but we wanted to make sure we had the right information in place, as well as a plan to address what you're facing.

For context, we released a new version of the Codecov action about a week ago. Since then we noticed an uptick with some larger repos such as yourself with regards to being rate limited, which should explain what you're experiencing.

We're looking to have a fix for this out very soon. Once that's in, I would encourage you to try using the Codecov app again.

**Comment by rohan-at-sentry** [comment] 2024-02-09 22:00
@skateman @ssbarnea  thanks for your patience on this. I have updates

We've identified the root cause of this issue - it would seem that there are some open source repos that can be set to use integration on an older way of authenticating on codecov which caused Codecov to ignore the repo/org Github bot and default to Codecov's bot. This caused us to start hitting Github rate limits pretty frequently leading to the issues y'all are seeing.

We should have a patch for this up Monday, with more improvements to come in the back half of next week

**Comment by rohan-at-sentry** [comment] 2024-02-12 21:51
@ssbarnea @skateman - we've shipped a fix for this today. I'll keep the issue open for the rest of this week - pl let us know if you see similar issues crop up

**Comment by skateman** [comment] 2024-02-13 05:57
@rohan-at-sentry it works now, thank you! 💯 🎉

**Closed** 2024-02-20 15:12 UTC
Labels: Waiting for: Product Owner, Bug
